# give_artifacts.mcfunction
# Generated by Archaeology Artifacts Generator
# Total artifacts: 51

# Stone Brick Debris (Tag: 1)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.650f,0.232f,-0.638f,0.342f]
#give @p stone_bricks[custom_name='{"bold":true,"color":"dark_gray","text":"Stone Brick Debris"}',lore=['{"color":"gray","text":"A chunk of stone brick debris."}'],custom_data={tag:1,scale:[0.5f,0.5f,0.5f],rotation:[0.650f,0.232f,-0.638f,0.342f]}] 1

# Cobble Debris (Tag: 2)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.170f,-0.805f,0.319f,0.470f]
#give @p cobblestone[custom_name='{"bold":true,"color":"dark_gray","text":"Cobble Debris"}',lore=['{"color":"gray","text":"A chunk of cobblestone debris."}'],custom_data={tag:2,scale:[0.5f,0.5f,0.5f],rotation:[0.170f,-0.805f,0.319f,0.470f]}] 1

# Brick Debris (Tag: 3)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.008f,-0.453f,-0.419f,0.787f]
#give @p brick[custom_name='{"bold":true,"color":"dark_gray","text":"Brick Debris"}',lore=['{"color":"gray","text":"A loose brick."}'],custom_data={tag:3,scale:[0.5f,0.5f,0.5f],rotation:[-0.008f,-0.453f,-0.419f,0.787f]}] 1

# Terracotta Debris (Tag: 4)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.802f,0.586f,-0.106f,-0.041f]
#give @p terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of terracotta debris."}'],custom_data={tag:4,scale:[0.5f,0.5f,0.5f],rotation:[0.802f,0.586f,-0.106f,-0.041f]}] 1

# White Terracotta Debris (Tag: 5)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.028f,0.825f,-0.419f,0.379f]
#give @p white_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"White Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of white terracotta debris."}'],custom_data={tag:5,scale:[0.5f,0.5f,0.5f],rotation:[-0.028f,0.825f,-0.419f,0.379f]}] 1

# Red Terracotta Debris (Tag: 6)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.743f,-0.244f,-0.589f,0.202f]
#give @p red_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Red Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of red terracotta debris."}'],custom_data={tag:6,scale:[0.5f,0.5f,0.5f],rotation:[-0.743f,-0.244f,-0.589f,0.202f]}] 1

# Orange Terracotta (Tag: 7)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.271f,-0.569f,-0.594f,0.500f]
#give @p orange_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Orange Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of orange terracotta debris."}'],custom_data={tag:7,scale:[0.5f,0.5f,0.5f],rotation:[-0.271f,-0.569f,-0.594f,0.500f]}] 1

# Purple Terracotta (Tag: 8)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.523f,-0.581f,-0.426f,0.454f]
#give @p purple_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Purple Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of purple terracotta debris."}'],custom_data={tag:8,scale:[0.5f,0.5f,0.5f],rotation:[-0.523f,-0.581f,-0.426f,0.454f]}] 1

# Magenta Terracotta (Tag: 9)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.051f,-0.799f,-0.100f,0.591f]
#give @p magenta_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Magenta Terracotta Debris"}',lore=['{"color":"gray","text":"A chunk of magenta terracotta debris."}'],custom_data={tag:9,scale:[0.5f,0.5f,0.5f],rotation:[0.051f,-0.799f,-0.100f,0.591f]}] 1

# Chest Latch (Tag: 10)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.286f,0.447f,-0.475f,0.702f]
#give @p tripwire_hook[custom_name='{"bold":true,"color":"dark_gray","text":"Chest Latch"}',lore=['{"color":"gray","text":"A latch that once would have held"}','{"color":"gray","text":"together a chest long decayed."}'],custom_data={tag:10,scale:[0.5f,0.5f,0.5f],rotation:[0.286f,0.447f,-0.475f,0.702f]}] 1

# Barrel Hoop (Tag: 11)
# Scale: [1.0f,1.0f,1.0f], Rotation: [0.255f,0.623f,-0.520f,0.526f]
#give @p chain[custom_name='{"bold":true,"color":"dark_gray","text":"Barrel Hoop"}',lore=['{"color":"gray","text":"The metal hoop of a barrel"}','{"color":"gray","text":"long decayed."}'],custom_data={tag:11,scale:[1.0f,1.0f,1.0f],rotation:[0.255f,0.623f,-0.520f,0.526f]}] 1

# Salt (Tag: 12)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.342f,0.459f,-0.790f,0.221f]
#give @p sugar[custom_name='{"bold":true,"color":"dark_gray","text":"Salt"}',lore=['{"color":"gray","text":"A pile of salt, the container"}','{"color":"gray","text":"that once held it long decayed."}'],custom_data={tag:12,scale:[0.5f,0.5f,0.5f],rotation:[0.342f,0.459f,-0.790f,0.221f]}] 1

# Charred Wheat Seeds (Tag: 13)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.312f,0.822f,0.459f,0.130f]
#give @p melon_seeds[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Wheat Seeds"}',lore=['{"color":"gray","text":"The charred remains of"}','{"color":"gray","text":"wheat seeds."}'],custom_data={tag:13,scale:[0.5f,0.5f,0.5f],rotation:[-0.312f,0.822f,0.459f,0.130f]}] 1

# Charred Wheat (Tag: 14)
# Scale: [1.0f,1.0f,1.0f], Rotation: [-0.265f,0.057f,0.643f,-0.717f]
#give @p dried_kelp[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Wheat"}',lore=['{"color":"gray","text":"The charred remains of"}','{"color":"gray","text":"wheat."}'],custom_data={tag:14,scale:[1.0f,1.0f,1.0f],rotation:[-0.265f,0.057f,0.643f,-0.717f]}] 1

# Rat Bones (Tag: 15)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.205f,-0.750f,-0.171f,-0.606f]
#give @p bone[custom_name='{"bold":true,"color":"dark_gray","text":"Rat Bones"}',lore=['{"color":"gray","text":"The bones of a rat."}'],custom_data={tag:15,scale:[0.5f,0.5f,0.5f],rotation:[0.205f,-0.750f,-0.171f,-0.606f]}] 1

# Silver Fork (Tag: 16)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.223f,0.891f,-0.019f,0.395f]
#give @p trident[custom_name='{"bold":true,"color":"dark_gray","text":"Silver Fork"}',lore=['{"color":"gray","text":"A silver fork."}'],custom_data={tag:16,scale:[0.5f,0.5f,0.5f],rotation:[-0.223f,0.891f,-0.019f,0.395f]}] 1

# Silver Knife (Tag: 17)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.763f,0.507f,0.393f,0.082f]
#give @p iron_sword[custom_name='{"bold":true,"color":"dark_gray","text":"Silver Knife"}',lore=['{"color":"gray","text":"A silver knife."}'],custom_data={tag:17,scale:[0.5f,0.5f,0.5f],rotation:[-0.763f,0.507f,0.393f,0.082f]}] 1

# Clay Cup (Tag: 18)
# Scale: [0.8f,0.8f,0.8f], Rotation: [-0.751f,-0.384f,-0.522f,0.130f]
#give @p flower_pot[custom_name='{"bold":true,"color":"dark_gray","text":"Clay Cup"}',lore=['{"color":"gray","text":"A broken clay cup."}'],custom_data={tag:18,scale:[0.8f,0.8f,0.8f],rotation:[-0.751f,-0.384f,-0.522f,0.130f]}] 1

# Cooking Pot (Tag: 19)
# Scale: [1.0f,1.0f,1.0f], Rotation: [-0.190f,-0.624f,-0.187f,0.735f]
#give @p cauldron[custom_name='{"bold":true,"color":"dark_gray","text":"Cooking Pot"}',lore=['{"color":"gray","text":"A large cooking pot."}'],custom_data={tag:19,scale:[1.0f,1.0f,1.0f],rotation:[-0.190f,-0.624f,-0.187f,0.735f]}] 1

# Copper Coin (Tag: 20)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.280f,-0.355f,0.868f,-0.204f]
#give @p copper_ingot[custom_name='{"bold":true,"color":"dark_gray","text":"Copper Coin"}',lore=['{"color":"gray","text":"A copper coin that is"}','{"color":"gray","text":"minted into a small"}','{"color":"gray","text":"round shape, about"}','{"color":"gray","text":"1-inch across."}'],custom_data={tag:20,scale:[0.5f,0.5f,0.5f],rotation:[0.280f,-0.355f,0.868f,-0.204f]}] 1

# Key (Tag: 21)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.780f,0.249f,-0.206f,0.535f]
#give @p trial_key[custom_name='{"bold":true,"color":"dark_gray","text":"Key"}',lore=['{"color":"gray","text":"A copper key that"}','{"color":"gray","text":"looks like it could"}','{"color":"gray","text":"open some pretty"}','{"color":"gray","text":"hefty doors."}'],custom_data={tag:21,scale:[0.5f,0.5f,0.5f],rotation:[0.780f,0.249f,-0.206f,0.535f]}] 1

# Iron Door (Tag: 22)
# Scale: [1.5f,1.5f,1.5f], Rotation: [-0.172f,-0.750f,-0.494f,0.405f]
#give @p iron_door[custom_name='{"bold":true,"color":"dark_gray","text":"Iron Door"}',lore=['{"color":"gray","text":"An iron door that"}','{"color":"gray","text":"looks like it would"}','{"color":"gray","text":"have been hard to"}','{"color":"gray","text":"break through."}'],custom_data={tag:22,scale:[1.5f,1.5f,1.5f],rotation:[-0.172f,-0.750f,-0.494f,0.405f]}] 1

# Golden Ring (Tag: 23)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.808f,-0.187f,0.095f,0.551f]
#give @p gold_ingot[custom_name='{"bold":true,"color":"dark_gray","text":"Golden Ring"}',lore=['{"color":"gray","text":"A golden ring of"}','{"color":"gray","text":"excellent craftsmanship."}'],custom_data={tag:23,scale:[0.5f,0.5f,0.5f],rotation:[-0.808f,-0.187f,0.095f,0.551f]}] 1

# Gold Nugget (Tag: 24)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.557f,0.759f,-0.036f,0.336f]
#give @p gold_nugget[custom_name='{"bold":true,"color":"dark_gray","text":"Gold Nugget"}',lore=['{"color":"gray","text":"A chunk of gold."}'],custom_data={tag:24,scale:[0.5f,0.5f,0.5f],rotation:[-0.557f,0.759f,-0.036f,0.336f]}] 1

# Silver Ring (Tag: 25)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.508f,-0.085f,0.841f,-0.165f]
#give @p iron_ingot[custom_name='{"bold":true,"color":"dark_gray","text":"Silver Ring"}',lore=['{"color":"gray","text":"A silver ring of"}','{"color":"gray","text":"excellent craftsmanship."}'],custom_data={tag:25,scale:[0.5f,0.5f,0.5f],rotation:[-0.508f,-0.085f,0.841f,-0.165f]}] 1

# Silver Nugget (Tag: 26)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.177f,0.135f,-0.886f,0.407f]
#give @p iron_nugget[custom_name='{"bold":true,"color":"dark_gray","text":"Silver Nugget"}',lore=['{"color":"gray","text":"A chunk of silver."}'],custom_data={tag:26,scale:[0.5f,0.5f,0.5f],rotation:[0.177f,0.135f,-0.886f,0.407f]}] 1

# Tweezers (Tag: 27)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.482f,0.539f,-0.674f,-0.153f]
#give @p shears[custom_name='{"bold":true,"color":"dark_gray","text":"Tweezers"}',lore=['{"color":"gray","text":"A pair of tweezers"}','{"color":"gray","text":"made of iron."}'],custom_data={tag:27,scale:[0.5f,0.5f,0.5f],rotation:[0.482f,0.539f,-0.674f,-0.153f]}] 1

# Iron Sword (Tag: 28)
# Scale: [1.0f,1.0f,1.0f], Rotation: [0.007f,0.097f,0.377f,0.921f]
#give @p iron_sword[custom_name='{"bold":true,"color":"dark_gray","text":"Iron Sword"}',lore=['{"color":"gray","text":"An iron sword."}'],custom_data={tag:28,scale:[1.0f,1.0f,1.0f],rotation:[0.007f,0.097f,0.377f,0.921f]}] 1

# Iron Pickaxe (Tag: 29)
# Scale: [1.0f,1.0f,1.0f], Rotation: [0.030f,0.153f,0.367f,0.917f]
#give @p iron_pickaxe[custom_name='{"bold":true,"color":"dark_gray","text":"Iron Pickaxe"}',lore=['{"color":"gray","text":"An iron pickaxe."}'],custom_data={tag:29,scale:[1.0f,1.0f,1.0f],rotation:[0.030f,0.153f,0.367f,0.917f]}] 1

# Iron Hoe (Tag: 30)
# Scale: [1.0f,1.0f,1.0f], Rotation: [0.390f,0.513f,0.327f,0.691f]
#give @p iron_hoe[custom_name='{"bold":true,"color":"dark_gray","text":"Iron Hoe"}',lore=['{"color":"gray","text":"An iron hoe."}'],custom_data={tag:30,scale:[1.0f,1.0f,1.0f],rotation:[0.390f,0.513f,0.327f,0.691f]}] 1

# Cow Bones (Tag: 31)
# Scale: [1.0f,1.0f,1.0f], Rotation: [-0.206f,-0.602f,-0.097f,0.766f]
#give @p bone[custom_name='{"bold":true,"color":"dark_gray","text":"Cow Bones"}',lore=['{"color":"gray","text":"The bones of a cow,"}','{"color":"gray","text":"likely the ribs."}'],custom_data={tag:31,scale:[1.0f,1.0f,1.0f],rotation:[-0.206f,-0.602f,-0.097f,0.766f]}] 1

# Pig Bones (Tag: 32)
# Scale: [0.8f,0.8f,0.8f], Rotation: [-0.862f,0.463f,-0.196f,0.067f]
#give @p bone[custom_name='{"bold":true,"color":"dark_gray","text":"Pig Bones"}',lore=['{"color":"gray","text":"The bones of a pig,"}','{"color":"gray","text":"likely the ribs."}'],custom_data={tag:32,scale:[0.8f,0.8f,0.8f],rotation:[-0.862f,0.463f,-0.196f,0.067f]}] 1

# Charred Steak (Tag: 33)
# Scale: [0.8f,0.8f,0.8f], Rotation: [0.501f,0.553f,-0.425f,0.512f]
#give @p cooked_beef[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Steak"}',lore=['{"color":"gray","text":"The charred remains"}','{"color":"gray","text":"of an overcooked"}','{"color":"gray","text":"steak."}'],custom_data={tag:33,scale:[0.8f,0.8f,0.8f],rotation:[0.501f,0.553f,-0.425f,0.512f]}] 1

# Charred Bread (Tag: 34)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.070f,0.808f,0.206f,0.547f]
#give @p black_dye[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Bread"}',lore=['{"color":"gray","text":"The charred remains"}','{"color":"gray","text":"of a loaf of bread."}'],custom_data={tag:34,scale:[0.5f,0.5f,0.5f],rotation:[-0.070f,0.808f,0.206f,0.547f]}] 1

# White Stained Glass Debris (Tag: 35)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.056f,-0.769f,-0.593f,0.232f]
#give @p white_stained_glass_pane[custom_name='{"bold":true,"color":"dark_gray","text":"White Stained Glass Debris"}',lore=['{"color":"gray","text":"Some shards of white"}','{"color":"gray","text":"stained glass."}'],custom_data={tag:35,scale:[0.5f,0.5f,0.5f],rotation:[-0.056f,-0.769f,-0.593f,0.232f]}] 1

# Red Stained Glass Debris (Tag: 36)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.225f,0.455f,-0.280f,0.815f]
#give @p red_stained_glass_pane[custom_name='{"bold":true,"color":"dark_gray","text":"Red Stained Glass Debris"}',lore=['{"color":"gray","text":"Some shards of red"}','{"color":"gray","text":"stained glass."}'],custom_data={tag:36,scale:[0.5f,0.5f,0.5f],rotation:[-0.225f,0.455f,-0.280f,0.815f]}] 1

# Glass Debris (Tag: 37)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.038f,-0.952f,-0.273f,0.134f]
give @p glass_pane[custom_name='{"bold":true,"color":"dark_gray","text":"Glass Debris"}',lore=['{"color":"gray","text":"Some shards of glass."}'],custom_data={tag:37,scale:[0.5f,0.5f,0.5f],rotation:[-0.038f,-0.952f,-0.273f,0.134f]}] 1

# Clay Flute (Tag: 38)
# Scale: [0.8f,0.8f,0.8f], Rotation: [-0.177f,-0.081f,0.056f,0.979f]
give @p lightning_rod[custom_name='{"bold":true,"color":"dark_gray","text":"Clay Flute"}',lore=['{"color":"gray","text":"A clay flute of"}','{"color":"gray","text":"decent craftsmanship."}'],custom_data={tag:38,scale:[0.8f,0.8f,0.8f],rotation:[-0.177f,-0.081f,0.056f,0.979f]}] 1

# End Rod (Tag: 39)
# Scale: [0.8f,0.8f,0.8f], Rotation: [0.351f,-0.915f,-0.195f,-0.030f]
give @p end_rod[custom_name='{"bold":true,"color":"dark_gray","text":"Bone Flute"}',lore=['{"color":"gray","text":"A bone flute of"}','{"color":"gray","text":"decent craftsmanship."}'],custom_data={tag:39,scale:[0.8f,0.8f,0.8f],rotation:[0.351f,-0.915f,-0.195f,-0.030f]}] 1

# Green Game Piece (Tag: 40)
# Scale: [0.3f,0.3f,0.3f], Rotation: [-0.645f,0.089f,0.689f,0.318f]
give @p green_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Green Game Piece"}',lore=['{"color":"gray","text":"A green clay game piece,"}','{"color":"gray","text":"likely used in a board"}','{"color":"gray","text":"game of some type."}'],custom_data={tag:40,scale:[0.3f,0.3f,0.3f],rotation:[-0.645f,0.089f,0.689f,0.318f]}] 1

# Blue Game Piece (Tag: 41)
# Scale: [0.3f,0.3f,0.3f], Rotation: [0.255f,0.690f,-0.109f,0.669f]
give @p blue_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Blue Game Piece"}',lore=['{"color":"gray","text":"A blue clay game piece,"}','{"color":"gray","text":"likely used in a board"}','{"color":"gray","text":"game of some type."}'],custom_data={tag:41,scale:[0.3f,0.3f,0.3f],rotation:[0.255f,0.690f,-0.109f,0.669f]}] 1

# Yellow Game Piece (Tag: 42)
# Scale: [0.3f,0.3f,0.3f], Rotation: [0.768f,-0.064f,-0.154f,0.618f]
give @p yellow_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Yellow Game Piece"}',lore=['{"color":"gray","text":"A yellow clay game piece,"}','{"color":"gray","text":"likely used in a board"}','{"color":"gray","text":"game of some type."}'],custom_data={tag:42,scale:[0.3f,0.3f,0.3f],rotation:[0.768f,-0.064f,-0.154f,0.618f]}] 1

# Red Game Piece (Tag: 43)
# Scale: [0.3f,0.3f,0.3f], Rotation: [-0.296f,-0.313f,-0.786f,0.444f]
give @p red_terracotta[custom_name='{"bold":true,"color":"dark_gray","text":"Red Game Piece"}',lore=['{"color":"gray","text":"A red clay game piece,"}','{"color":"gray","text":"likely used in a board"}','{"color":"gray","text":"game of some type."}'],custom_data={tag:43,scale:[0.3f,0.3f,0.3f],rotation:[-0.296f,-0.313f,-0.786f,0.444f]}] 1

# Game Board (Tag: 44)
# Scale: [0.8f,0.8f,0.8f], Rotation: [0.657f,0.006f,-0.178f,-0.732f]
give @p heavy_weighted_pressure_plate[custom_name='{"bold":true,"color":"dark_gray","text":"Game Board"}',lore=['{"color":"gray","text":"A high-quality game board"}','{"color":"gray","text":"made with an iron border"}','{"color":"gray","text":"with a clay face. There"}','{"color":"gray","text":"appear to be the faded"}','{"color":"gray","text":"remains of a unique grid"}','{"color":"gray","text":"pattern with 4 different"}','{"color":"gray","text":"colored regions."}'],custom_data={tag:44,scale:[0.8f,0.8f,0.8f],rotation:[0.657f,0.006f,-0.178f,-0.732f]}] 1

# Scroll of Spirit (Tag: 45)
# Scale: [1.0f,1.0f,1.0f], Rotation: [-0.690f,0.265f,-0.370f,-0.563f]
give @p written_book[written_book_content={title:"Epistle to the Godwinites",author:"Scroll of Spirit",pages:['["Epistle to the Godwinites\\n 1 Grace to you and peace from our Lord GOD, the Most Merciful, Singular, and Omnipotent. 2 I am Owyn Son of Godwin, servant of the Lord, called to prophetic vocation in His service."]','["3 Verily, brother, the Lord GOD has given no compulsion in faith. 4 And verily you are commended for your virtue, for your people keep fast to their fealty. 5 But a tremendous sin arises in your home."]','["6 The Lord GOD is the Lord GOD without peer, but you sons of Godwin give Him a vulgar and worldly name, and ascribe to Him many partners."]','["7 And this is a sin of tremendous quality, for none but the Lord resides in the Seventh Sky, and it is His throne. 8 Even Horen, who spoke the Virtue, falls short of GOD."]','["9 So I find that professing yourselves to be wise, you have made yourselves fools. 10 You have traded the glory of the Lord GOD without peer for the imperfections of men. 11 Even in our time we bear the failure of Horen, for the corruption of Iblees lasts."]','["12 Would you worship fallible men? 13 The greatness of GOD is in His fullness and His purity. 14 But your stories raise men up with GOD for their power or their virtue."]','["15 Shall I worship the strong man? 16 Shall you worship the tallest among you? 17 No, for the glory of GOD is not in mere magnitude, but in His fullness and His perfection."]','["18 Verily, brother, the Lord GOD is the whole and only god. 19 And verily you must find sole salvation in His laws, for there are none alike to Him."]','["20 So to you Sons of Godwin, I admonish: There are no partners to GOD. 21 He is foremost in the sky and has no equal, no part, no manifestation. 22 In His name, I beg you, brother, turn away from false gods and seek salvation in the One."]']},custom_data={tag:45,scale:[1.0f,1.0f,1.0f],rotation:[-0.690f,0.265f,-0.370f,-0.563f]}] 1

# Scroll of Virtue (Tag: 46)
# Scale: [0.8f,0.8f,0.8f], Rotation: [-0.583f,-0.408f,0.602f,-0.362f]
give @p written_book[written_book_content={title:"Canticle of Humility",author:"Scroll of Virtue",pages:['["Canticle of Humility\\n 1 Lo and attend, for I am the Lord GOD, and I am in the foremost part of heaven. 2 Though the spring flower withers and the fruit of the tree falls to the ground, My Word lasts into the eve of the world, and the fruit of virtue cannot rot."]','["3 I am the Lord GOD without peer. 4 I created the earth, the seas, and the heavens. 5 And I breathed life into the beasts of the earth and the men who rule them."]','["6 And as I am eternal, you are transient, and there is no eternity without Me."]','["7 For I have given to you a theater of virtue, and I have ordered the estates of the world. 8 And you shall be without pretense or conceit, for before the mountain, the ant and the aurochs are equally small."]','["9 So I am the Most High, and in pursuit of My Virtue, I bid my faithful this: You shall not judge your own virtue, be it great or small, for all fall short of Me."]','["10 And I am the Lord GOD without peer, and My power is the only power, and My eternity is the only eternity, and all the aeons of the Virtue shall sustain the righteous."]']},custom_data={tag:46,scale:[0.8f,0.8f,0.8f],rotation:[-0.583f,-0.408f,0.602f,-0.362f]}] 1

# Haeseni Military Etiquette (Tag: 47)
# Scale: [0.8f,0.8f,0.8f], Rotation: [0.093f,-0.295f,0.477f,0.823f]
give @p written_book[written_book_content={title:"Haenseti Military Etiquette",author:"Ser Alric Sigmar Ruthern",pages:['["Haenseti Military Etiquette",{"text":"\\nby Ser Alric Sigmar Ruthern"}]','["Etiquette is essential in military practice.","\\nThe HRA is a brotherhood, but soldiers must conduct themselves properly on and off the field."]','["As a member of the HRA, you represent Haense,","\\nits Royal Family, and its people. Upholding its values earns respect."]','["Ranks of the HRA:","\\n- Lord Marshal","\\n- Captain","\\n- Lieutenant","\\n- Sergeant","\\n- Armiger","\\n- Armsman","\\n- Footman","\\n- Initiate"]','["GLOSSARY","\\nFormality - Court, duty, or uniformed settings.","\\nCasualness - Informal settings like the tavern.","\\nSuperior - Officers above Armiger.","\\nOn Duty - In uniform.","\\nOff Duty - Out of uniform."]','["ADDRESSING SUPERIORS","\\n- Address the Lord Marshal as ‘Lord Marshal’.","\\n- Address superior officers as ‘Sir’.","\\n- Address knights as ‘Ser’.","\\n- Monarchs are ‘Your Majesty’ with a nod.","\\n- Nobles and officials require proper titles."]','["SALUTING & POSTURE","\\n- Salute all superiors above Armiger.","\\n- Always salute the highest officer present.","\\n- In formal settings, hold until ‘At ease’."]','["- When unsure, assume formality.","\\n- Stand and salute when a superior enters.","\\n- Knights must always be saluted.","\\n- Stand at attention with heels together."]','["EXPECTATIONS OF BEHAVIOR","\\n- Soldiers must act with discipline.","\\n- Use diplomacy over hostility.","\\n- Speak clearly, not abrasively.","\\n- Seek peaceful resolutions first."]','["- In formation, only speak when commanded.","\\n- Do not question orders from a superior.","\\n- Public insubordination is unacceptable.","\\n- Obey commands both on and off duty."]']},custom_data={tag:47,scale:[0.8f,0.8f,0.8f],rotation:[0.093f,-0.295f,0.477f,0.823f]}] 1

# Human Bones (Tag: 48)
# Scale: [0.9f,0.9f,0.9f], Rotation: [-0.130f,0.699f,0.176f,0.681f]
give @p bone[custom_name='{"bold":true,"color":"dark_gray","text":"Crushed Human Bones"}',lore=['{"color":"gray","text":"The crushed bones of"}','{"color":"gray","text":"an unfortunate human"}','{"color":"gray","text":"long ago."}'],custom_data={tag:48,scale:[0.9f,0.9f,0.9f],rotation:[-0.130f,0.699f,0.176f,0.681f]}] 1

# Dark Oak Wood Debris (Tag: 49)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.739f,0.623f,0.229f,-0.119f]
give @p dark_oak_slab[custom_name='{"bold":true,"color":"dark_gray","text":"Dark Oak Wood Debris"}',lore=['{"color":"gray","text":"A small chunk of dark"}','{"color":"gray","text":"oak planks that have"}','{"color":"gray","text":"yet to decay."}'],custom_data={tag:49,scale:[0.5f,0.5f,0.5f],rotation:[-0.739f,0.623f,0.229f,-0.119f]}] 1

# Dark Oak Log Debris (Tag: 50)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.473f,0.372f,-0.732f,-0.320f]
give @p dark_oak_log[custom_name='{"bold":true,"color":"dark_gray","text":"Dark Oak Log Debris"}',lore=['{"color":"gray","text":"A small chunk of dark"}','{"color":"gray","text":"oak log that has yet"}','{"color":"gray","text":"to decay."}'],custom_data={tag:50,scale:[0.5f,0.5f,0.5f],rotation:[0.473f,0.372f,-0.732f,-0.320f]}] 1

# Charcoal (Tag: 51)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.486f,0.469f,-0.512f,0.530f]
give @p charcoal[custom_name='{"bold":true,"color":"dark_gray","text":"Charcoal"}',lore=['{"color":"gray","text":"A chunk of charcoal."}'],custom_data={tag:51,scale:[0.5f,0.5f,0.5f],rotation:[-0.486f,0.469f,-0.512f,0.530f]}] 1

