# give_artifacts.mcfunction
# Generated by Archaeology Artifacts Generator
# Total artifacts: 6

# Grinding Stone (Tag: 1)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.726f,-0.050f,-0.673f,0.134f]
give @p smooth_stone[custom_name='{"bold":true,"color":"dark_gray","text":"Grinding Stone"}',lore=['{"color":"gray","italic":true,"text":"A worn stone tool used for grinding grains into flour. This stone shows heavy use, with small grooves and wear patterns indicating it was frequently used for food preparation."}'],custom_data={tag:1,scale:[0.5f,0.5f,0.5f],rotation:[-0.726f,-0.050f,-0.673f,0.134f]}] 1

# Charred Wheat Seeds (Tag: 2)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.075f,-0.671f,-0.122f,0.728f]
give @p melon_seeds[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Wheat Seeds"}',lore=['{"color":"gray","italic":true,"text":"The blackened appearance indicates they were exposed to intense heat."}'],custom_data={tag:2,scale:[0.5f,0.5f,0.5f],rotation:[-0.075f,-0.671f,-0.122f,0.728f]}] 1

# Charred Lump of Bread (Tag: 3)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.124f,-0.338f,0.904f,-0.229f]
give @p black_dye[custom_name='{"bold":true,"color":"dark_gray","text":"Charred Lump of Bread"}',lore=['{"color":"gray","italic":true,"text":"A lump of ancient bread, burnt to a crisp."}'],custom_data={tag:3,scale:[0.5f,0.5f,0.5f],rotation:[0.124f,-0.338f,0.904f,-0.229f]}] 1

# Clay Tablet (Tag: 4)
# Scale: [0.8f,0.8f,0.8f], Rotation: [0.846f,-0.328f,0.226f,0.355f]
give @p friend_pottery_sherd[custom_name='{"bold":true,"color":"dark_gray","text":"Clay Tablet"}',lore=['{"color":"gray","italic":true,"text":"This clay tablet bears etched symbols that resemble an early form of written language. The exact meaning of the symbols are unclear."}'],custom_data={tag:4,scale:[0.8f,0.8f,0.8f],rotation:[0.846f,-0.328f,0.226f,0.355f]}] 1

# Ash (Tag: 5)
# Scale: [0.5f,0.5f,0.5f], Rotation: [-0.215f,0.825f,-0.145f,0.502f]
give @p gunpowder[custom_name='{"bold":true,"color":"dark_gray","text":"Ash"}',lore=['{"color":"gray","italic":true,"text":"A lump of ash."}'],custom_data={tag:5,scale:[0.5f,0.5f,0.5f],rotation:[-0.215f,0.825f,-0.145f,0.502f]}] 1

# Iron Hoe (Tag: 6)
# Scale: [0.5f,0.5f,0.5f], Rotation: [0.793f,0.323f,0.515f,0.045f]
give @p iron_hoe[custom_name='{"bold":true,"color":"dark_gray","text":"Iron Hoe"}',lore=['{"color":"gray","italic":true,"text":"A well-crafted iron hoe, used for tilling soil and preparing land for planting."}'],custom_data={tag:6,scale:[0.5f,0.5f,0.5f],rotation:[0.793f,0.323f,0.515f,0.045f]}] 1
