# give_artifacts.mcfunction
# Generated by Archaeology Artifacts Generator
# Total artifacts: 1

# Flint Arrowhead (Tag: 1)
give @p flint[custom_name='{"bold":true,"color":"dark_gray","italic":true,"text":"Flint Arrowhead"}',lore=['"This is lore."','"This is lore also."'],custom_data={tag:1}] 1

